import { createRequire } from 'module'
const require = createRequire(import.meta.url)
require('dotenv').config({ path: '.env.local' })
import { prisma } from '../lib/prisma.js'

const newsArticles = [
  { title: "IRS Announces 2026 Standard Mileage Rates", slug: "irs-2026-mileage-rates", summary: "The IRS released 2026 standard mileage rates: 70 cents per mile for business, 21 cents for medical and military moves, 14 cents for charitable purposes. Businesses must update expense reimbursement policies and payroll systems immediately.", url: "https://www.irs.gov/newsroom/irs-issues-standard-mileage-rates-for-2026", source: "IRS", category: "Regulation Update", country: "US", sourceType: "automated", publishedAt: new Date("2026-02-27") },
  { title: "FICA Wage Base Rises to $176,100 for 2026", slug: "fica-wage-base-2026", summary: "The SSA confirmed the 2026 Social Security wage base increases to $176,100, up from $168,600. Employers must update payroll systems to apply the correct withholding ceiling from the first 2026 payroll run.", url: "https://www.ssa.gov/oact/cola/cbb.html", source: "SSA", category: "Payroll", country: "US", sourceType: "automated", publishedAt: new Date("2026-02-21") },
  { title: "IRS Expands R&D Tax Credit Payroll Offset for Small Businesses", slug: "irs-rd-credit-expansion-2026", summary: "New legislation increases the R&D payroll tax offset limit for qualifying small businesses from $250,000 to $500,000 annually. Eligible businesses can offset a larger share of qualifying research expenditures against employer payroll tax.", url: "https://www.irs.gov/businesses/small-businesses-self-employed/research-credit", source: "IRS", category: "Tax Compliance", country: "US", sourceType: "automated", publishedAt: new Date("2026-02-19") },
  { title: "IRS Issues Final Regulations on Digital Asset Broker Reporting", slug: "irs-1099-da-final-regulations", summary: "Brokers must issue Form 1099-DA for digital asset transactions beginning with the 2026 tax year. Businesses transacting in cryptocurrency must ensure cost basis tracking and accounting system integration are in place before the first 2026 transaction.", url: "https://www.irs.gov/forms-pubs/about-form-1099-da", source: "IRS", category: "Tax Compliance", country: "US", sourceType: "automated", publishedAt: new Date("2026-02-14") },
  { title: "IRS Updates W-4 and Publication 15-T Withholding Tables for 2026", slug: "irs-w4-2026-update", summary: "The IRS released the updated Form W-4 and Publication 15-T for 2026. Employers must use the 2026 withholding tables for all payroll runs from January 1 and should offer existing employees the option to update their withholding elections.", url: "https://www.irs.gov/forms-pubs/about-form-w-4", source: "IRS", category: "Payroll", country: "US", sourceType: "automated", publishedAt: new Date("2026-02-10") },
  { title: "HMRC Confirms MTD for ITSA Mandatory From April 2026", slug: "hmrc-mtd-itsa-mandatory-2026", summary: "HMRC confirmed Making Tax Digital for Income Tax Self Assessment is mandatory from April 6, 2026 for self-employed individuals and landlords with qualifying income above £50,000. Affected taxpayers must use HMRC-recognised software and register for MTD before the April deadline.", url: "https://www.gov.uk/guidance/sign-up-your-client-for-making-tax-digital-for-income-tax", source: "HMRC", category: "Regulation Update", country: "UK", sourceType: "automated", publishedAt: new Date("2026-02-26") },
  { title: "National Living Wage Rises to £12.21 Per Hour From April 2026", slug: "national-living-wage-2026", summary: "The National Living Wage increases to £12.21 per hour from April 1, 2026 for workers aged 21 and over — a 6.7% rise. The National Minimum Wage for 18-20 year olds rises to £10.00. All UK payroll systems must be updated before the April pay run.", url: "https://www.gov.uk/national-minimum-wage-rates", source: "HMRC", category: "Payroll", country: "UK", sourceType: "automated", publishedAt: new Date("2026-02-23") },
  { title: "UK Corporation Tax Confirmed at 25% for 2026-27", slug: "uk-corporation-tax-2026", summary: "HMRC confirmed corporation tax remains at 25% for profits above £250,000 and 19% for profits up to £50,000 for 2026-27. Marginal relief continues for profits between these thresholds. Companies should factor confirmed rates into dividend and tax planning decisions.", url: "https://www.gov.uk/guidance/corporation-tax-rates-and-reliefs", source: "HMRC", category: "Tax Compliance", country: "UK", sourceType: "automated", publishedAt: new Date("2026-02-20") },
  { title: "HMRC Finalises Basis Period Reform Transition Rules", slug: "hmrc-basis-period-reform-2026", summary: "HMRC published final guidance on basis period reform for self-employed individuals with non-April year ends. Overlap relief claims and transitional profit spreading rules for the 2025-26 return are now confirmed. Affected taxpayers should engage their accountant immediately to model the tax impact.", url: "https://www.gov.uk/guidance/basis-period-reform", source: "HMRC", category: "Tax Compliance", country: "UK", sourceType: "automated", publishedAt: new Date("2026-02-17") },
  { title: "DWP Launches Auto-Enrolment Contribution Rate Consultation", slug: "auto-enrolment-consultation-2026", summary: "The Department for Work and Pensions opened a consultation on increasing auto-enrolment minimum contributions to 12% total by 2030. Employers should model the payroll cost impact of proposed phased increases and begin scenario planning for higher contribution obligations.", url: "https://www.gov.uk/guidance/workplace-pensions-for-employers", source: "DWP", category: "Payroll", country: "UK", sourceType: "automated", publishedAt: new Date("2026-02-12") },
  { title: "ATO Super Guarantee Rate Increases to 12% From 1 July 2026", slug: "ato-sgc-12-percent-2026", summary: "The Superannuation Guarantee rate increases from 11.5% to 12% from July 1, 2026, completing the legislated schedule. All payroll systems must be updated before the first pay period of the 2026-27 financial year. Failure to pay the correct rate attracts the SGC charge plus penalties.", url: "https://www.ato.gov.au/businesses-and-organisations/super-for-employers/paying-super-contributions/how-much-super-to-pay", source: "ATO", category: "Payroll", country: "AU", sourceType: "automated", publishedAt: new Date("2026-02-25") },
  { title: "ATO Targets Work-From-Home Claims as 2026 Compliance Priority", slug: "ato-wfh-compliance-2026", summary: "The ATO identified WFH expense claims as a compliance focus for 2025-26 returns. Taxpayers using the 67 cents per hour fixed rate must maintain actual records of hours worked from home throughout the year. The ATO confirmed reconstructed records will not be accepted.", url: "https://www.ato.gov.au/individuals-and-families/income-deductions-offsets-and-records/deductions-you-can-claim/working-from-home-expenses", source: "ATO", category: "Tax Compliance", country: "AU", sourceType: "automated", publishedAt: new Date("2026-02-22") },
  { title: "ATO Extends Small Business Lodgement Penalty Amnesty to May 2026", slug: "ato-amnesty-2026", summary: "The ATO extended the small business lodgement penalty amnesty to cover overdue income tax returns, BAS, and FBT returns lodged by May 31, 2026. Eligible businesses can have failure-to-lodge penalties remitted by bringing lodgements current before the deadline.", url: "https://www.ato.gov.au/newsroom", source: "ATO", category: "Regulation Update", country: "AU", sourceType: "automated", publishedAt: new Date("2026-02-18") },
  { title: "ATO Updates Contractor vs Employee Guidance After High Court Rulings", slug: "ato-contractor-classification-2026", summary: "The ATO published updated guidance on employee versus contractor classification following recent High Court decisions. Businesses must now assess the totality of the working relationship, not just contract terms. Misclassification exposes firms to unpaid SGC, PAYG withholding, and substantial penalties.", url: "https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/employee-or-contractor", source: "ATO", category: "Regulation Update", country: "AU", sourceType: "automated", publishedAt: new Date("2026-02-11") },
  { title: "CRA Confirms 2026 CPP Contribution Rates and Maximums", slug: "cra-cpp-2026", summary: "The CRA confirmed 2026 CPP rates: 5.95% for employees and employers on earnings between $3,500 and $73,200. CPP2 applies at 4% on earnings between $73,200 and $81,900. Payroll systems must calculate both tiers correctly from the first 2026 payroll run.", url: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/payroll-deductions-contributions/canada-pension-plan-cpp.html", source: "CRA", category: "Payroll", country: "CA", sourceType: "automated", publishedAt: new Date("2026-02-28") },
  { title: "CRA Reinstates Bare Trust T3 Reporting for 2025 Tax Year", slug: "cra-bare-trust-t3-2025", summary: "After waiving bare trust T3 filing requirements for 2023 and 2024, the CRA confirmed all bare trusts must file a T3 return and Schedule 15 for the 2025 tax year. Failure to file attracts penalties of $25 per day to a maximum of $2,500.", url: "https://www.canada.ca/en/revenue-agency/services/tax/trust-administrators/t3-return.html", source: "CRA", category: "Tax Compliance", country: "CA", sourceType: "automated", publishedAt: new Date("2026-02-15") },
  { title: "CRA SR&ED Program Guidance Updated for 2026 Claimants", slug: "cra-sred-2026", summary: "The CRA published updated SR&ED guidance clarifying eligible work criteria following recent tax court decisions. The refundable ITC rate for CCPCs remains 35% on the first $3M of qualifying expenditures. Enhanced reviews continue for claims above $250,000.", url: "https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program.html", source: "CRA", category: "Tax Compliance", country: "CA", sourceType: "automated", publishedAt: new Date("2026-02-09") },
  { title: "FINTRAC Updates AML Obligations for Accounting Businesses", slug: "fintrac-aml-accounting-2026", summary: "FINTRAC updated its compliance guidance for accounting and bookkeeping businesses as designated reporting entities. Key changes include revised customer due diligence requirements and clarified suspicious transaction reporting obligations under the PCMLTFA.", url: "https://fintrac-canafe.canada.ca/guidance-directives/overview-apercu/Guide1/1-eng", source: "FINTRAC", category: "Regulation Update", country: "CA", sourceType: "automated", publishedAt: new Date("2026-02-06") },
  { title: "OECD Pillar Two Implementation Status Update 2026", slug: "oecd-pillar-two-2026", summary: "The OECD confirmed that the UK, EU member states, Australia, Canada, and over 50 jurisdictions have enacted Pillar Two domestic top-up tax legislation. Multinational groups with consolidated revenues above EUR 750M must assess effective tax rate exposure in every jurisdiction.", url: "https://www.oecd.org/tax/beps/", source: "OECD", category: "Tax Compliance", country: "General", sourceType: "automated", publishedAt: new Date("2026-02-12") },
  { title: "IFRS 18 Replaces IAS 1 — Key Changes for Financial Statement Presentation", slug: "ifrs-18-ias-1-replacement", summary: "IFRS 18 Presentation and Disclosure in Financial Statements is mandatory for periods from January 1, 2027. Key changes include a revised income statement with defined categories, new management performance measure disclosure requirements, and enhanced aggregation guidance. Preparation should begin now.", url: "https://www.ifrs.org/issued-standards/list-of-standards/ifrs-18-presentation-and-disclosure-in-financial-statements/", source: "IFRS Foundation", category: "Regulation Update", country: "General", sourceType: "automated", publishedAt: new Date("2026-02-08") }
]

async function main() {
  try {
    const deleted = await prisma.newsArticle.deleteMany({})
    const created = await prisma.newsArticle.createMany({ data: newsArticles })
    console.log(`Deleted news articles: ${deleted.count}`)
    console.log(`Created news articles: ${created.count}`)
  } catch (error) {
    console.error('Error seeding news:', error)
  } finally {
    await prisma.$disconnect()
  }
}

main()
